### ISSUE TITLE
请问一下 报这个错怎么处理呢 Function.prototype.apply was called on [object Object], which is a object and not a function

### ISSUE THREAD

**Issue by zhz-we** [antvis/FEngine#180]
这个是wx小程序的

执行完
`yarn add @antv/f-wx   `
然后构建 npm 
接下来就报一个
 Function.prototype.apply was called on [object Object], which is a object and not a function
![image](https://user-images.githubusercontent.com/42529417/229466282-4a982bc1-174e-4dc8-a5ae-9861d59df127.png)

**Comment by RilyZhang** [comment]
我也遇到了，同问

**Comment by CAI-JIEMING** [comment]
同问，相同报错

**Comment by zengyue** [comment]
一些底层依赖问题，已修掉了
