### ISSUE TITLE
请问微信小程序，报这个错是什么原因？

### ISSUE THREAD

**Issue by pangxiaodun** [antvis/FEngine#212]
用官网文档中的示例报错。
<img width="598" alt="image" src="https://github.com/antvis/FEngine/assets/22793431/c781c759-8e15-4d03-ba62-629a9a27a5be">

直接用github的项目跑起来也报错。
<img width="701" alt="image" src="https://github.com/antvis/FEngine/assets/22793431/90b7c280-95f3-4a44-96ca-7eb66f2c45b6">

**Comment by zengyue** [comment]
已经修复了
